name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    outputs:
      has_changesets: ${{ steps.changesets.outputs.hasChangesets }}
      should_publish: ${{ steps.publish-check.outputs.should_publish }}
    permissions:
      contents: write
      issues: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          package-manager-cache: false
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Update npm
        run: npm install -g npm@^11.15.0

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          version: npm run version
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for unpublished package versions
        if: steps.changesets.outputs.hasChangesets == 'false'
        id: publish-check
        run: node .github/scripts/has-unpublished-packages.mjs

  publish:
    name: Stage package
    needs: release
    if: needs.release.outputs.should_publish == 'true'
    environment:
      name: npm
      url: https://www.npmjs.com/package/preact-render-to-string
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          package-manager-cache: false
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Update npm
        run: npm install -g npm@^11.15.0

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build package
        run: npm run build

      - name: Stage package
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          publish: node .github/scripts/stage-package.mjs
          commitMode: github-api
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
